name: Node.js CI
on:
  push:
    branches: [dev, main, nuxt-upgrade]
  pull_request:
    branches: [dev, main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm i
      - run: npm run lint
