  name: Node.js CI
  on:
    push:
      branches: [ * ]
    pull_request:
      branches: [ * ]
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
        - run: npm i
        - run: npm lint
